### ISSUE TITLE
1px offset in Safari 9.0.1 on OS X 10.11.1 (FlexSlider 2.6.0)

### ISSUE THREAD

**Issue by noahkuhn** [woocommerce/FlexSlider#1470] opened 2015-12-16 16:28 UTC
I'm not sure when this crept into FlexSlider, but I'm now seeing a 1px "border" on the left side of my slides. It's not an actual CSS border, simply that 1px of the previous (left) slide is showing "outside" the flex-viewport. If the slide CSS has a background, and an image to the left like I have, it appears like a border is there. This does not happen in Firefox or Chrome on the same machine. See screenshot for an example of the offset. The only CSS I changed from the default theme was to remove the 4px border on .flexslider

![screen shot 2015-12-16 at 11 22 38 am](https://cloud.githubusercontent.com/assets/1133909/11846735/e50fe062-a3e7-11e5-9237-4d3d4c574dfd.png)

**Comment by noahkuhn** [comment] 2015-12-16 16:33
For what it's worth, if I use the web inspector to alter the translate3d style on .slides to add a single pixel, it works properly on Safari. For example, a 1160px slide:

By default, this style on safari has a 1px edge 
translate3d(-1160px, 0px, 0px);

If I add a pixel, it bumps it over one and looks correct.
translate3d(-1161px, 0px, 0px);

Clearly not the solution, but a starting point for why Safari might be off by 1px?

**Comment by noahkuhn** [comment] 2015-12-16 16:41
Final debugging image. It appears that the extra pixel is actually outside the .flexslider and .flex-viewport div, despite .flex-viewport having overflow:hidden on it.
![screen shot 2015-12-16 at 11 35 18 am](https://cloud.githubusercontent.com/assets/1133909/11847130/ea089c42-a3e9-11e5-9596-ff6d299faec5.png)

**Comment by noahkuhn** [comment] 2015-12-16 16:54
The plot thickens. This only happens when the browser window is a certain width. Basically on alternating pixel widths of browser window, the offset is wrong. If you drag your window width very slowly, it appears and reappears every pixel change. If your browser window is showing say 1200 pixels, the offset is correct, 1201 pixels, broken, 1202 pixels, correct.

Made a quick screen capture video to demonstrate: http://sendvid.com/vm0r9ip0

**Comment by noahkuhn** [comment] 2015-12-16 17:00
Additional: This is on a retina Macbook Pro. It only happens if I am plugged into a non-retina monitor. It doesn't happen if I am viewing on the actual retina screen.

**Comment by whooehoo** [comment] 2016-01-12 14:31
I have the same problem. Macbook Air NON-retina, Safari 9.0.1, OS X 10.11.1.
![2016-01-12 17 14 23](https://cloud.githubusercontent.com/assets/11571567/12265820/7662ff5e-b950-11e5-9504-e0ac32ea94d4.png)
Debug image absolutely the same as the author's sample.

**Comment by greenroy** [comment] 2016-01-16 12:05
I am finding the same issue on an iPad in portrait mode. Tried debugging with inspect element and can't seem to fix anything.

http://s24.postimg.org/5ndxus7id/IMG_0236.png

**Comment by svenHoskens** [comment] 2016-01-20 09:24
![screen shot 2016-01-20 at 10 22 04](https://cloud.githubusercontent.com/assets/13624194/12444513/ad8c340e-bf5f-11e5-9fd7-1e39d1de01d5.png)

I have the same issue. (partial screenshot above)
It only happens on the left side of my slider. I'm using owl carousel, not FlexSlider, so it looks to me like this isn't an issue with our respective libraries but rather with Safari rendering on non-retina screens. (this never happens on the native screen of my macbook, only on my second Dell screen)

It looks to me like a rounding issue in Safari. The issue does not reproduce on Chrome, so it ain't a problem of webkit either.

**Comment by greenroy** [comment] 2016-01-20 09:49
Seems a strange one. I'm not sure about it being just Safari. I also saw this on iPad Mini running Chrome (portrait mode only).

**Comment by svenHoskens** [comment] 2016-01-20 09:59
Hmmm, what's the overlap here? Both browsers are of course webkit, but Chrome renders correctly on non-retina displays on my Macbook. Does anyone know the differences in Webkit on a Macbook vs an iPad Mini? Perhaps Chrome uses a newer version of webkit which fixed this problem?

**Comment by mortendk** [comment] 2016-01-21 21:52
I can confirm that this happens on retina screen & safari and only that combo - or if you test it in apples iOs simulator. ooooh happy days ;)

**Comment by thisma** [comment] 2016-01-27 11:46
This issue occurs in Safari on OS X on every display and computer I have tested it. the issue appears to happen exactly half the time, depending on the window width. It only shifts left, never right.

Looking forward to 2.7.0!

**Comment by MediadesignAshley** [comment] 2016-02-09 10:37
Here is a quick fix below. It isn't perfect but seems to do the job.

Firstly I changed the width of the image from 100% to the below figure. This hides the previous slides 1px visibility:

.flexslider .slides img {
  width: 99.99999%;
}

Doing the above will now reveal 1px of the flexsliders' background color. This can easily be set to none:

.flexslider {
  background:none;
}

**Comment by alexjarvis** [comment] 2016-03-07 23:28
Interestingly this seems to be fixed in Safari 9.1 which is available in the 10.11.4 beta.

**Comment by ewape** [comment] 2016-03-15 16:12
If anyone is interested - I have added transform: scale(1.005) to .flex-viewport and it seems to be patching this problem for now.

**Comment by noahkuhn** [comment] 2016-03-25 19:39
Upgraded to 10.11.4 with Safari 9.1 and this issue is still there for me. ewape's workaround doesn't seem to work for me.

**Comment by pureawesome** [comment] 2016-04-07 19:34
Anyone else have any luck with this?

**Comment by pureawesome** [comment] 2016-04-07 19:45
Set useCSS to false and that fixed it for me.

**Comment by marcdittmann** [comment] 2016-04-15 15:04
My Solution was to add this to the img:

```
.flexslider .slides img {
...
-webkit-backface-visibility: hidden;
-webkit-transform: translateZ(0) scale(1.0, 1.0);
}
```

**Comment by Ras-Al-Cool** [comment] 2016-04-19 09:18
Hey I had this problem too, in main.css there's a style:

`.flexslider .slides li {
        position: relative;
        left: -1px;
    }
}`

Changing left to 0px solved the problem for me.

**Comment by lanceharman** [comment] 2016-07-13 18:16
I was experiencing this issue but it would fix itself if there was any movement from the slider or the window. I added `$(window).trigger('resize')` immediately after the init which works in a hackey way.

**Comment by BenRacicot** [comment] 2017-07-31 18:35
Confirm that this exists.

**Comment by jeffikus** [comment] 2017-08-01 10:04
@BenRacicot I'm gonna need a live URL of some sorts to see what you are experiencing please.

**Comment by BenRacicot** [comment] 2017-08-01 14:11
@jeffikus thanks for your response. I've actually taken down the page with the example. I just wanted to confirm that a mysterious 1px offset exists one some instances of Flexslider slides. I was on v2.5. Sorry I can't provide an example.

**Comment by jeffikus** [comment] 2017-08-01 18:52
Ok, thanks.

**Closed by jeffikus** 2017-08-01 18:52 UTC

**Comment by BenRacicot** [comment] 2018-02-06 18:06
@jeffikus I have a new implementation online with this problem on Flexslider 2.7. This appears on Chrome 63 and 64 on MacOS.

![flexslider-bug-chrome 63 0 3239 132-edit](https://user-images.githubusercontent.com/1815385/35875794-614dfd7a-0b3e-11e8-9699-e68951365700.png)

Perhaps you could take a look to see how and why? It may be that I am doing something wrong that inhibits the correct width calculations onload but I cannot figure it out and replicating it is difficult as well. (browserstack)

Thanks for your help!

**Comment by snegurova** [comment] 2021-07-30 12:28
![image](https://user-images.githubusercontent.com/24573435/127652889-a16a306a-f2ce-4d36-9575-5462daaed17f.png)
