### ISSUE TITLE
FlexSlider WooThemes Live Demo not working in Firefox 56-57

### ISSUE THREAD

**Issue by MarbleMadness** [woocommerce/FlexSlider#1679] opened 2017-11-09 23:43 UTC
As of the latest version of Firefox (56) FlexSlider does not display properly. To observe this issue, direct your Firefox 56 browser to the WooThemes FlexSlider 2 live demo.

http://flexslider.woothemes.com/index.html

The live demo may work on its initial page load, but reloading the page or switching to a different example results in the images being hidden from view.

Resizing the browser horizontally causes the slider to begin displaying correctly.

I have been trying to come up with a workaround by changing the Javascript or CSS to trigger the same effect as resizing the browser, but have had no success so far.

Can someone please suggest either a fix or other ideas for a workaround?

**Comment by MarbleMadness** [comment] 2017-11-17 17:37
This issue first appeared in Firefox 56.0. It persists in Firefox 57.0 (Quantum).

**Comment by jeffikus** [comment] 2018-02-05 08:24
Hi there, I've done a big update to the demo's, please let me know if the issue persists on your side. Thanks

**Comment by webkees** [comment] 2018-03-07 10:28
Okay, we will let you know. Up to now, the issue is NOT solved. Your demopage AND your script on own websites ist NOT working in FF 58.0 Quantum, but as far as I can judge ONLY on Windows 64-bit. My co-worker tested it on a MacPro in FF 58.0 Quantum und found no problems.

**Comment by jeffikus** [comment] 2018-03-08 14:13
@danieldudzic - please confirm and let me know.

**Comment by webkees** [comment] 2018-03-08 14:39
Tested this on a Notebook running on Win 10 Pro CU, 1709 and there it worked. The Build # is not the same though. On the Notebook the Build # is 16299.125
Is this a Windows-Issue???

**Comment by danieldudzic** [comment] 2018-03-08 20:20
![dashboard](https://user-images.githubusercontent.com/905781/37174327-762eede0-2316-11e8-9666-65dbbc646678.png)

![ms0fy5gyxm](https://user-images.githubusercontent.com/905781/37172579-86c630a0-2311-11e8-964b-0ccc3129c326.png)


@jeffikus I was able to replicate using Browser Stack, on both Mac and Windows with any Firefox 56+ version I tried.

**Comment by alexvibealex** [comment] 2018-10-04 11:45
same issue here. any quick fix for this ? When its going to be reolve?

**Closed** 2024-08-26 05:26 UTC
